force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Records_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Export.recordType-meta.xml
<RecordType>
    <fullName>Export</fullName>
    <active>true</active>
    <label>Export</label>
</RecordType>

force-app/main/default/objects/Order__c/recordTypes/Import.recordType-meta.xml
<RecordType>
    <fullName>Import</fullName>
    <active>true</active>
    <label>Import</label>
</RecordType>

force-app/main/default/classes/BAFCOUploadOrderBlob.cls
@RestResource(urlMapping='/getOrderBlob/*')
global class BAFCOUploadOrderBlob {
    @HttpGet
    global static String getOrderBlob() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String rUrlId = req.requestURI.split('getOrderBlob/')[1];
        if(rUrlId != null){
            PageReference pdf = null;
            Order__c OrderObj = [Select id,Order_Type__c from order__c where id =: rUrlId limit 1];
            if(OrderObj.Order_Type__c == 'Sea Import') pdf = Page.BAFCOOrderImportPDFPage;
            else if(OrderObj.Order_Type__c == 'Air Export' || OrderObj.Order_Type__c == 'Air Import') pdf = Page.BAFCOAirOrderPDFPage;
            else pdf = Page.BAFCOOrderPDFPage;
            pdf.getParameters().put('recordId',(String)rUrlId);
            pdf.getParameters().put('showShippLine','true');
            pdf.getParameters().put('showCharges','true');
            pdf.getParameters().put('nooverride', '1');
            pdf.setRedirect(true);
            Blob b = null;
            if(Test.isRunningTest()) { 
                b = blob.valueOf('Unit.Test');
            }
            else{
                b = pdf.getContentAsPdf();
            }
			return FormData.writeFileBody('test',b,'orderPdf');
        }
        return null;
    }
}